name: framework_install_base
on:
  pull_request:
    paths:
      - pyproject.toml

jobs:
  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.10.9
          - 3.7.1
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download files
        uses: actions/checkout@v3

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment
        run: .venv/bin/activate

      - name: Install QA framework
        run: pip install .

      - name: Run unit tests
        run: python -m pytest tests/ --tb=short

  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version:
          - 3.10.9
          - 3.7.1
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download files
        uses: actions/checkout@v3

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment
        run: source .\venv\Scripts\activate

      - name: Install QA framework
        run: pip install .

      - name: Run unit tests
        run: python -m pytest tests/ --tb=short
