---
- name: Debian/Ubuntu | Install ca-certificates and gnupg
  become: true
  apt:
    name:
      - ca-certificates
      - gnupg
    state: present
  register: wazuh_agent_ca_package_install
  until: wazuh_agent_ca_package_install is succeeded

- name: Debian/Ubuntu | Install apt-transport-https and acl
  become: true
  apt:
    name:
      - apt-transport-https
      - acl
    state: present
  register: wazuh_agent_ca_package_install
  until: wazuh_agent_ca_package_install is succeeded
  when: not (ansible_distribution == "Debian" and ansible_distribution_major_version in ['11'])

- name: Debian/Ubuntu | Installing Wazuh repository key (Ubuntu 14)
  become: true
  shell: |
    set -o pipefail
    curl -s {{ wazuh_repo.gpg }} | apt-key add -
  args:
    warn: false
    executable: /bin/bash
  changed_when: false
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int == 14
    - not wazuh_custom_packages_installation_agent_enabled

- name: Debian/Ubuntu | Installing Wazuh repository key
  become: true
  apt_key:
    url: "{{ wazuh_repo.gpg }}"
    id: "{{ wazuh_repo.key_id }}"
  when:
    - not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int == 14)
    - not wazuh_custom_packages_installation_agent_enabled

- name: Debian/Ubuntu | Add Wazuh repositories
  become: true
  apt_repository:
    filename: wazuh_repo
    repo: "{{ wazuh_repo.apt }}"
    state: present
    update_cache: true
  when:
    - not wazuh_custom_packages_installation_agent_enabled

- name: Linux Debian | Install wazuh-agent
  become: true
  apt:
    name: "wazuh-agent={{ wazuh_agent_version }}-*"
    state: present
    cache_valid_time: 3600
  when:
    - ansible_os_family|lower != "redhat"
    - not wazuh_custom_packages_installation_agent_enabled
    - not ansible_check_mode
  tags:
    - init

- name: Remove Wazuh repository (and clean up left-over metadata)
  become: true
  apt_repository:
    repo: "{{ wazuh_repo.apt }}"
    state: absent
  changed_when: false
